name: My test

on: [workflow_dispatch]

jobs:
  ubuntu-job:
      runs-on: ubuntu-latest
      steps:
        - name: multiline shell command
          run: |
            echo "Hello"
            mvn -version
            npm -v
        - name: something in python
          shell: python
          run: |
            import platform
            print (platform.processor())
  windows-job:
    runs-on: windows-latest
    needs: ["ubuntu-job"]
    steps:
      - name: directory in Powershell
        run: Get-Location
      - name: directory in Bash!
        shell: bash
        run: pwd
            
  
  
     
     

