

name: Actions workflow (udemy2)

on:
  - push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Simple JS Acttion
        #id to reference in next step
        id: id_greet
        uses: actions/hello-world-javascript-action@v1
        #input parameter
        with: 
          who-to-greet: Ewa
      - name: Use previous step output
        #reference output from prev. step
        run: echo "${{steps.id_greet.outputs.time}}"
        
  run-checkout-action:
    runs-on: ubuntu-latest

    steps:
      - name: check ls returns no files
        run: |
          echo "directory listing"
          ls
      - name: Checkout action
        uses: actions/checkout@v2.3.1
        #NOTE, could also just run git clone
      - name: check ls does retunr files
        run: |
          echo "directory listing:"
          ls
          
        

