

name: Actions workflow (udemy2)

on:
  - push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Simple JS Acttion
        #id to reference in next step
        id: id_greet
        uses: actions/hello-world-javascript-action@v1
        #input parameter
        with: 
          who-to-greet: Ewa
      - name: Use previous step output
        #reference output from prev. step
        run: echo "${{steps.id_greet.outputs.time}}"
        
  run-checkout-action:
    runs-on: ubuntu-latest

    steps:
      - name: check ls returns no files
        run: |
          echo "directory listing"
          ls
      - name: Checkout action
        uses: actions/checkout@v2.3.1
      - name: check ls does retunr files
        run: |
          echo "directory listing:"
          ls
      #NOTE, could also just run git clone, with usage of some variables
      # git clone git@github:$GITHUB_REPOSITORY 
      # or so :-)
      - name: list github-related variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          
          
        

