

name: Actions workflow (udemy2)

on:
  - push

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Simple JS Acttion
        #id to reference in next step
        id: id_greet
        uses: actions/hello-world-javascript-action@v1
        #input parameter
        with: 
          who-to-greet: Ewa
      - name: Use previous step output
        #reference output from prev. step
        run: echo "${{steps.id_greet.outputs.time}}"
        

